{% set name = "asyncclick" %}
{% set version = "8.2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asyncclick-{{ version }}.tar.gz
  sha256: 6eccb64f0b6422eec911c363709fd50a84e3166eb8b3841184a4d457fdc57911

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - anyio
    - python >=3.7
    - colorama
    - importlib-metadata

test:
  imports:
    - asyncclick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://palletsprojects.com/p/click/
  summary: Composable command line interface toolkit, async version
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - awvwgk
