{% set name = "asyncclick" %}
{% set version = "8.1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncclick-{{ version }}.tar.gz
  sha256: a47b61258a689212cf9463fbf3b4cc52d05bfd03185f6ead2315fc03fd17ef75

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - anyio
    - python >=3.7
    - colorama
    - importlib-metadata

test:
  imports:
    - asyncclick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://palletsprojects.com/p/click/
  summary: Composable command line interface toolkit, async version
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - awvwgk
